### ISSUE TITLE
Failure to load GormConnectionInspector model for objects

### ISSUE THREAD

**Issue by NormHarrison** [gnustep/apps-gorm#20] opened 2022-03-29 06:30 UTC
Hi, there seems to be a problem preventing the connection inspector, specifically for objects, from being loaded.

I must say thought, this does seem like it would be such a commonly used feature that someone would have already encountered it, so I do wonder if this is a local issue (using Debian 11).

Regardless, the steps to reproduce are:
1. Create a new Gorm project.
2. Select any object under the "Objects" pane of the main Gorm document window.
3. Go to the Inspector window and use the pop-up button at the top of the window to select the "Connections" option.

This results in the view failing to load and the pop-up menu getting awkwardly stuck on the screen. Continuing to try and open it will eventually result in a segmentation fault.

Gorm itself emits messages about what is occurring via standard out/error, which looks as follow each time the above is attempted:
```
Exception occurred while loading model: expected double and got int
Failed to load Gorm
Couldn't load GormConnectionInsector
```
The "Couldn't load GormConnectionInsector" (message seems to have a slight typo too) originates on [line 95 of GormConnectionInspector.m](https://github.com/gnustep/apps-gorm/blob/b36ec0e29a9f0a6bda49ca4a449eb8f388bcca32/GormCore/GormConnectionInspector.m#L95), where I assume the serialized nib is loaded from local storage, and somewhere in the collection of classes it houses (or maybe inherits from), an incorrect value is provided for the specific data type it's expecting.

Again, I could see this possibly being an issue specific to my version of the application, and I am still very new to Objective-C and GNUStep, so my assumptions above could be incorrect. I cloned the copy of Gorm I'm using from this repository on Monday and compiled it with a version of the core libraries that I downloaded (also from these project's Github) a few months ago (maybe that could be part of it). So if this is a non-issue, please disregard.

Thank you.

**Comment by gcasa** [comment] 2023-03-17 07:52
I've checked this on the latest release and I am unable to reproduce it.   Typically this kind of "expected x and got y" error comes from a mismatch between gnustep-gui and the version of the .gorm file being loaded.   Gorm is tightly associated with the version of gnustep-gui that is released so it's important to use the latest Gorm with the latest gnustep-gui.   I am closing this for now, please re-open it if you see this again.   
![gorm_issue_20](https://user-images.githubusercontent.com/27943/225844972-43b0ac2d-c749-4052-8dec-95da3fa123f3.png)

**Closed by gcasa** 2023-03-17 07:52 UTC
